version: '3.4'
services:
  node-monitor-service:
    build:
      context: .
    network_mode: "host" 
    ports:
      - "9999:9999"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - LOCAL_RESP_IP_PORT=
      - LOCAL_RECIVE_IP_PORT=
      - REMOTE_MONITOR_IP_PORT=
      - NOTIFICATION_EMAIL=
      - NOTIFICATION_EMAIL_PASSWORD=
      - SUBJECT_EMAIL=
      - CONTEXT=server_failure
      - GOPATH=/root/go
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/go/bin:/root/go/bin:/root/go/bin
