version: '3.4'
services:
  ackresp-service:
    build:
      context: .
    network_mode: "host" 
    ports:
      - "9999:9999"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - LOCAL_RESP_IP_PORT=
      - GOPATH=/root/go
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/go/bin:/root/go/bin:/root/go/bin
